### ISSUE TITLE
Using more specific post type name for storing rewrite rules

### ISSUE THREAD

**Issue by adiloztaser** [buddypress/bp-rewrites#28]
BP Rewrites is currently creating a custom post type called `buddypress`. I think we shouldn't use our main plugins name as a custom post type. I suggest to use `bp-rewrites` instead of `buddypress`. Any thoughts?

**Comment by imath** [comment]
I’d say, as the end goal is to merge the plugin into Core it’s ok to use `buddypress` imho. The name can be important for template hierarchy in the future.

imath
https://imathi.eu
________________________________
De : Adil Öztaşer ***@***.***>
Envoyé : Tuesday, February 15, 2022 7:23:14 AM
À : buddypress/bp-rewrites ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [buddypress/bp-rewrites] Using more specific post type name for storing rewrite rules (Issue #28)


BP Rewrites is currently creating a custom post type called buddypress. I think we shouldn't use our main plugins name as a custom post type. I suggest to use bp-rewrites instead of buddypress. Any thoughts?

**Comment by adiloztaser** [comment]
Thanks for sharing your opinion. It seems there is nothing to do.
