### ISSUE TITLE
Fatal error with custom members nav item 

### ISSUE THREAD

**Issue by adiloztaser** [buddypress/bp-rewrites#33]
I have a custom navigation item for members component. It occours a fatal error when BP-Rewrites is active. The reason of this error `nav` property creating just for admin requests.  Is there any reason to do it?

https://github.com/buddypress/bp-rewrites/blob/91a6d6addb844f8286317be00e5824370e0d8a74/src/bp-members/classes/class-members-component.php#L100-L103

Here is my mu-plugin to see the fatal error:

```php
<?php
namespace NefisYemekTarifleri\Custom_Nav;

add_action( 'bp_init', __NAMESPACE__ . '\\init', 999999 );
function init() {
	if ( function_exists( 'bp_core_new_nav_item' ) ) {
		bp_core_new_nav_item(
			array(
				'name'            => 'Custom Nav',
				'slug'            => 'custom-nav',
				'parent_slug'     => buddypress()->members->slug,
				'position'        => 10,
				'screen_function' => __NAMESPACE__ . '\\custom_nav_screen',
			)
		);
	}
}

function custom_nav_screen() {
	do_action( 'bp_members_screen_display_profile' );
	bp_core_load_template( apply_filters( 'bp_members_screen_display_profile', 'members/single/home' ) );
}
```

Error:
```
Fatal error: Uncaught Error: Call to a member function add_nav() on null
in /var/www/html/wp-content/plugins/buddypress/src/bp-core/bp-core-buddybar.php on line 172
```

**Comment by imath** [comment]
Hi @adiloztaser 

Thanks a lot for your report. Actually the real problem is you are creating a custom nav at `bp_init` when BP Rewrites is modifying this to happen at `bp_parse_query` on front end. To reply to your question, as `bp_parse_query` is not fired into the WP Admin context, I've added the part you mentioned to make sure to generate the nav into the WP Admin context 😉 . 

See https://github.com/buddypress/bp-rewrites/blob/trunk/inc/functions.php#L462|L465 

I thought navigations were created using the `'bp_' . $component_id . '_setup_nav'` which seems the right time to do it, but we never wrote documentation about it.

1. Could you try using this action `bp_members_setup_nav` instead of `bp_init` ?
2. We probably need to find a way to prevent these situations using a specific back compat mechanism or at list provide an explanation like a `_doing_it_wrong()` notice because I believe using `bp_init` to generate a custom nav, even without BP Rewrites, is wrong 😄

**Comment by adiloztaser** [comment]
Hi @imath,

Thanks for explanation the situation. I was thinking it should work with BP-Rewrites as well If it works with Core.

> Could you try using this action bp_members_setup_nav instead of bp_init ?

I tried to use `bp_members_setup_nav` action but it's not fired even if BP-Rewrites deactivated because of the if statement I added link below.

https://github.com/buddypress/buddypress/blob/c35521aa20a7dd67c654e508572fe96dfbf601fd/src/bp-members/classes/class-bp-members-component.php#L429-L433

It seems `bp_core_setup_nav` action is the right way to setup custom nav item for members component.

> We probably need to find a way to prevent these situations using a specific back compat mechanism or at list provide an explanation like a _doing_it_wrong() notice

This sounds great to me.
