### ISSUE TITLE
Load order difference makes current group unavailable at `bp_setup_globals`

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/bp-rewrites#7]
**Describe the bug**
My buddypress-docs plugin uses a `BP_Group_Extension` to add an item to group navigation. The nav item is properly loaded, and the `BP_Group_Extension` `display()` method properly called, with bp-rewrites activated.

However, the logic inside of my `display()` method depends on some other setup that buddypress-docs does at runtime, including determining the current "view" based in part on `bp_current_component()`. The particular line in question is https://github.com/boonebgorges/buddypress-docs/blob/130328dc3000d22c35e642950b10b8a17454cfd7/includes/integration-groups.php#L113: without `bp-rewrites`, `bp_is_current_component( 'groups' )` (and `bp_get_current_group()`, `bp_is_group()`, etc) works properly, but with `bp-rewrites`, it incorrectly returns false.

It appears that this is because `current_component` etc are made available much later in the load process with `bp-rewrites`:

- Without `bp-rewrites`: `bp_core_set_uri_globals()` happens at `bp_init:2`, which is hooked to WP's `'init'`
- With `bp-rewrites`: Component `parse_query()` methods are hooked to WP's `'parse_query'`

The specific way that `buddypress-docs` operates here is based on very old legacy code. If I switched it so that my `BP_Group_Extension` directly checked the global at display time, instead of depending on a global that's set very early in the page load, it would work properly. However, this compatibility break might point to a broader problem with plugins that expect `current_component` etc to be available before `parse_query`.

I'm unsure if this will simply have to be a documented break, or if there's a way to shim the globals so that they're available earlier for backward compatibility reasons.

**To Reproduce**
1. Install and activate `buddypress-docs`
2. Visit a group
3. Click on 'Docs' nav item
4. You'll see that the plugin templates aren't loaded into the content area

**Expected behavior**
buddypress-docs content appears in group content area

**Comment by imath** [comment]
Hi @boonebgorges 

Thanks a lot for testing BP Rewrites with BP Docs 😍. So far the plugin only makes sure to set these globals. I totally agree we need to address this backward compatibility issue. I've been thinking about it lately and I believe we could do:

- document the change
- add a `_doing_it_wrong()` if these functions are called before the `bp_parse_query` hook happened
- in this case (when the function was called before  `bp_parse_query`), we could use the Legacy URL parser to return the result needed by the plugin. I'm thinking of using a slightly different version of `bp_core_set_uri_globals()` so that it stores the variables in another global.
- define a delay for the availability of this deprecated use. Eg: next 2 major BP versions.

What do you think of it?

**Comment by boonebgorges** [comment]
Thanks for the quick response @imath !

> in this case (when the function was called before bp_parse_query), we could use the Legacy URL parser to return the result needed by the plugin. I'm thinking of using a slightly different version of bp_core_set_uri_globals() so that it stores the variables in another global.

Is it possible to load the bp-rewrites engine early in these cases, rather that using a `bp_core_set_uri_globals()` shim? I guess the danger here is that we'll encourage plugins to register their own rewrite rules in such a way that they can't reliably be bootstrapped at `init`? I also see that, for example, the plugin's `bp_parse_query` calls `is_main_query()`, and WP doesn't let you call these sorts of methods before `'wp'` (well before `parse_query`, but well after `init`).

If this seems too problematic, then your strategy seems OK to me. I might suggest a magic `__get()` method on the `BuddyPress` global, which would detect calls to `current_component` etc.

**Comment by imath** [comment]
Thanks a lot for your advices and suggestions @boonebgorges 👍 . It's very helpful.

It's a complex challenge, but I'm confident we'll find the best way to migrate progressively!

**Comment by r-a-y** [comment]
I mentioned this during my previous attempt at doing rewrites: https://buddypress.trac.wordpress.org/ticket/4954#comment:13

> in this case (when the function was called before bp_parse_query), we could use the Legacy URL parser to return the result needed by the plugin. I'm thinking of using a slightly different version of bp_core_set_uri_globals() so that it stores the variables in another global.

In my patch, I did ~exactly~ a version of this with a new function, `bp_core_get_from_uri()` and the various `backpat_globals()` methods. See: https://buddypress.trac.wordpress.org/attachment/ticket/4954/4954.ray.01.patch

The only places where we would need backward compatibility are for the Members and Groups components AFAIK, but for other plugins with a custom root component, compatibility might be needed. I don't believe there are many BP plugins even doing this in 2021, but I could be wrong.

**Comment by imath** [comment]
Thanks a lot @r-a-y for pointing me on your patch. I'm going to check it and see how to include it into the plugin.

**Comment by imath** [comment]
Hi @boonebgorges #12 should fix the issue. From the BP Rewrites plugin I cannot change the `BuddyPress::__get()` magic method, but I agree the `_was_called_too_early()` check should be there once we merge the code into Core.

I'll work on #9 from another PR because I believe the Group Extension also needs some other adaptations in particular in the way it generates the Group nav.

Thanks again to you and @r-a-y for your help on tackling this issue 😍
